:concurrency: 25
:pidfile: tmp/pids/sidekiq.pid
:queues:
  - ["trip_requests", 1]
  - ["mailers", 1]
staging:
  :concurrency: 10
  :logfile: ./log/sidekiq.log
production:
  :concurrency: 20
  :logfile: ./log/sidekiq.log

