:pidfile: tmp/pids/sidekiq.pid
:concurrency: 5
:queues:
  - ["trip_requests", 1]
  - ["payment_transactions", 2]
  - ["mailers", 3]
staging:
  :logfile: log/sidekiq.log
  :concurrency: 4
production:
  :concurrency: 20
  :logfile: ./log/sidekiq.log
