:pidfile: tmp/pids/sidekiq.pid
:concurrency: 5
:queues:
  - ["trip_requests", 1]
  - ["mailers", 2]
staging:
  :logfile: log/sidekiq.log
  :concurrency: 3
production:
  :concurrency: 20
  :logfile: ./log/sidekiq.log
